import { PortfolioData } from "../types/portfolio";

export const PORTFOLIO_DATA: PortfolioData = {
  profile: {
    name: "Mostafa Mahmoud",
    title: "Senior Software Engineer",
    japaneseTitle: "モバイルアプリエンジニア • Mobile Software Engineer",
    contact: {
      email: "mostafasensei106@gmail.com",
      phone: "+201014414536",
      github: "MostafaSensei106",
      linkedin: "https://www.linkedin.com/in/mostafa-sensei106/",
      location: "Egypt",
      whatsapp: "201014414536",
      facebook: "https://www.facebook.com/MostafaSensei106",
      x: "https://x.com/MostafaSensei",
    },
    hero: {
      tagline: "High-Performance Systems & Elegant Mobile Ecosystems.",
      japaneseTagline: "高性能システムとエレガなモバイルエコシステム。",
      description: "Dedicated Software Engineer specialized in Flutter, Dart, Go (Gin), Rust, and Kotlin (Spring Boot / Android native). Crafting high performance, concurrent, and scalable solutions with a focus on technical excellence and user experience.",
      photo: "Assets/art-gallery/Images/logo/Mostafa.webp",
      cvUrl: "Assets/cv/Mostafa_Mahmoud_CV.pdf",
    },
  },
  experience: [
    {
      company: "GDGoC Benha University",
      link: "https://gdg.community.dev/gdg-on-campus-benha-university-benha-egypt",
      role: "Head of Flutter",
      location: "Benha, Egypt",
      period: "Oct 2024 – Present",
      description: "Leading the Flutter track: roadmap, workshops, and code review for student teams.",
      details: [
        "Building GDGoC Benha App V2 for events and bootcamp delivery.",
        "Maintaining a Flutter roadmap used by 200+ students.",
        "Running workshops on state management and clean architecture.",
        "Reviewing community projects and mentoring juniors."
      ],
      japaneseRole: "フラッター部門責任者",
    },
    {
      company: "Lothga",
      link: "https://lothgha.com/",
      role: "Flutter Developer [Volunteer]",
      location: "Jeddah, Saudi Arabia, SA",
      period: "Aug 2024 – Aug 2024",
      description: "Built the 'LothgaTablet' app shell: core structure, audio, and local data.",
      details: [
        "Implemented core app structure and shared kernel features.",
        "Added an audio layer for in-game feedback.",
        "Set up a central local database for game content.",
        "Added parental controls for progress and content.",
      ],
      japaneseRole: "フラッターデベロッパー",
    },
    {
      company: "Benha University",
      link: "https://www.bu.edu.eg/",
      role: "Bachelor of Computer Science",
      location: "Benha, Egypt",
      period: "Oct 2022 – May 2026",
      description: "Focusing on Software Engineering, Algorithms, and AI.",
      details: [
        "Studying Computer Science, building skills in programming and algorithms.",
      ],
      japaneseRole: "コンピューターサイエンス学士",
      isEducation: true,
    },
  ],
  projects: {
    githubUsername: "MostafaSensei106",
    pinnedRepos: [
      "Quantum-Crypto",
      "Waffle-DB",
      "Flutter-Dicom",
      "Network-Reachability",
      "FP-Growth",
      "Radix_Plus",
    ],
    highlights: [
      {
        name: "Flutter-Dicom",
        type: "Dart Package",
        description: "DICOM parsing and medical image rendering for Flutter, with a Rust core and GPU shaders. Benchmarks are linked in the repo.",
        metrics: ["Rust core", "DICOM", "GPU shaders"],
        link: "https://github.com/MostafaSensei106/Flutter-Dicom",
      },
      {
        name: "Network-Reachability",
        type: "Dart Package",
        description: "Network monitoring with multi-target probing and DNS resolution via a native core. Usage and limits are documented in the repo.",
        metrics: ["Rust core", "DNS probing", "Circuit breaker"],
        link: "https://github.com/MostafaSensei106/Network-Reachability",
      },
      {
        name: "Radix-Plus",
        type: "Dart Package",
        description: "Sorting helpers for large lists. Measured 7.0x vs List.sort() on the bench device in the repo (1M ints, see BENCHMARK.md).",
        metrics: ["1M-item bench in repo", "Isolates", "Zero-copy paths"],
        link: "https://github.com/MostafaSensei106/Radix_Plus",
      },
      {
        name: "FP-Growth",
        type: "Dart Package",
        description: "FP-Growth frequent-pattern mining. The 1M-transaction run (~1.46s) is the repo bench setup, not a general guarantee.",
        metrics: ["Isolate pool", "Memory-capped", "Bench script in repo"],
        link: "https://github.com/MostafaSensei106/fp_growth",
      },
      {
        name: "Quantum-Crypto",
        type: "Dart Package",
        description: "Post-quantum crypto suite for Flutter: NIST ML-KEM (FIPS 203) and ML-DSA (FIPS 204) over a Rust core. Bench numbers in the repo.",
        metrics: ["ML-KEM / ML-DSA", "Rust core", "AES-256-GCM"],
        link: "https://github.com/MostafaSensei106/Quantum-Crypto",
      },
      {
        name: "Waffle-DB",
        type: "Dart Package",
        description: "Local vector database for Flutter: Rust + HNSW indexing, 1536+ dimension embeddings with KNN search. Bench numbers in the repo.",
        metrics: ["HNSW index", "Rust core", "KNN search"],
        link: "https://github.com/MostafaSensei106/Waffle-DB",
      },
    ],
  },
  work: [
    {
      id: "tadamon-app",
      title: "Tadamon",
      type: "app",
      tagline: "Scan a product, get a clear on-device answer.",
      problem: "Shoppers needed a fast check without uploading photos.",
      role: "Flutter dev — Objectbox + Firestore sync, ML Kit scanning",
      stack: ["Flutter", "Dart", "BLoC", "Objectbox", "Firestore", "ML Kit"],
      platform: "Android / iOS",
      status: "open-source",
      year: "2024",
      links: { github: "https://github.com/MostafaSensei106/tadamon" },
      metrics: ["On-device scan", "Cloud sync", "BLoC"],
      featured: true,
    },
    {
      id: "lothga-tablet",
      title: "Lothga Tablet",
      type: "app",
      tagline: "Kids tablet shell with guarded content.",
      problem: "Private client app, not on GitHub. Needed one shell for many games plus parental controls.",
      role: "Flutter dev — shell, audio, local DB",
      stack: ["Flutter", "Dart", "Riverpod", "SQLite", "Audio"],
      platform: "Android Tablet",
      status: "private-demo",
      year: "2024",
      links: {},
      metrics: ["Single shell", "Parental controls", "Local-first"],
      featured: true,
    },
    {
      id: "gdg-benha-api",
      title: "GDGoC Benha API",
      type: "backend",
      tagline: "Events, attendance, and roles API.",
      problem: "Community app needed events, attendance, and roles without Firebase lock-in.",
      role: "Backend — Gin API, Postgres, Docker",
      stack: ["Go", "Gin", "Postgres", "Docker", "JWT"],
      platform: "REST API",
      status: "private-demo",
      year: "2025",
      links: {},
      metrics: ["REST + JWT", "Postgres", "Dockerized"],
      featured: true,
    },
    {
      id: "gopix-service",
      title: "GoPix Service",
      type: "backend",
      tagline: "Image pipeline behind the GoPix CLI.",
      problem: "Batch conversion needed checksums and parallel workers with clear errors.",
      role: "Go dev — workers, formats, CLI",
      stack: ["Go", "CLI", "Workers", "WebP/AVIF"],
      platform: "CLI + pipeline",
      status: "open-source",
      year: "2025",
      links: { github: "https://github.com/MostafaSensei106/gopix" },
      metrics: ["Parallel workers", "Checksum", "Multi-format"],
    },
    {
      id: "quotes-app",
      title: "Motivational Quotes",
      type: "app",
      tagline: "Shake the phone, get a quote with native feel.",
      problem: "Needed real sensor-driven interaction, not just a button.",
      role: "Flutter + Kotlin — platform channels, accelerometer",
      stack: ["Flutter", "Dart", "Kotlin", "Platform Channels"],
      platform: "Android",
      status: "open-source",
      year: "2025",
      links: {},
      metrics: ["Shake gesture", "Native bridge", "Clean arch"],
    },
    {
      id: "move-app",
      title: "Move App",
      type: "app",
      tagline: "Browse movies with cached, smooth lists.",
      problem: "Movie browsing needed caching, smooth images, and crash reports.",
      role: "Flutter dev — Hive cache, Dio, Sentry",
      stack: ["Flutter", "Dart", "BLoC", "Hive", "Dio", "Sentry"],
      platform: "Android / iOS",
      status: "open-source",
      year: "2025",
      links: {},
      metrics: ["Hive cache", "GetIt + Dio", "Sentry"],
    },
  ],
  services: [
    {
      id: "mobile",
      title: "Mobile Apps",
      japanese: "モバイル",
      description: "Flutter apps with native Kotlin bridges when needed, clean architecture and store-ready builds.",
      stack: ["Flutter", "Dart", "Kotlin", "Android Native"],
      deliverable: "Store build + docs",
    },
    {
      id: "backend",
      title: "Backend Systems",
      japanese: "バックエンド",
      description: "Backends with Go (Gin) or Kotlin (Spring Boot): REST APIs, auth, SQL & NoSQL data, caching, and Docker deploys.",
      stack: ["Go", "Gin", "Spring Boot", "SQL & NoSQL", "Docker"],
      deliverable: "API + compose file",
    },
    {
      id: "packages",
      title: "Packages & Perf",
      japanese: "パッケージ",
      description: "Dart/Go/Rust helpers with bench scripts and clear limits documented.",
      stack: ["Dart", "Go", "Rust", "FFI"],
      deliverable: "Package + bench",
    },
    {
      id: "mentoring",
      title: "Mentoring",
      japanese: "指導",
      description: "Flutter roadmaps and code review for student teams.",
      stack: ["Roadmap", "Review", "Workshops"],
      deliverable: "Roadmap + sessions",
    },
  ],
  stack: [
    { id: "mobile-stack", title: "Mobile", japanese: "モバイル", items: ["Flutter", "Dart", "Kotlin", "Android Native", "BLoC", "Objectbox", "Hive"] },
    { id: "backend-stack", title: "Backend", japanese: "バックエンド", items: ["Go", "Gin", "Spring Boot", "REST", "JWT", "Postgres", "SQLite", "Docker"] },
    { id: "core-stack", title: "Native Core", japanese: "コア", items: ["Rust", "FFI", "GPU Shaders", "ML Kit", "Platform Channels"] },
    { id: "tooling", title: "Tooling", japanese: "道具", items: ["Git", "Linux", "Docker", "CI/CD", "Sentry", "Dio"] },
  ],
  process: [
    { id: "brief", index: "01", title: "Brief", japanese: "要件", description: "Scope, platform, and what done looks like. Fixed deliverable list." },
    { id: "build", index: "02", title: "Build", japanese: "構築", description: "Thin slice first: working app or endpoint, then iterate." },
    { id: "measure", index: "03", title: "Measure", japanese: "計測", description: "Bench, latency, and edge cases. Numbers go in README." },
    { id: "harden", index: "04", title: "Harden", japanese: "強化", description: "Errors, empty states, and store/API docs. Then handover." },
  ],
  contributions: [
    {
      name: "Yaru.dart",
      org: "Ubuntu",
      description: "Type annotations, deprecation cleanup, and dependency upgrades for pub.dev compatibility.",
      link: "https://github.com/ubuntu/yaru.dart",
    },
    {
      name: "Toastification",
      org: "Dart Package",
      description: "Cut unused dependencies to shrink APK/AAB bundle sizes.",
      link: "https://github.com/payamzahedi/toastification",
    },
    {
      name: "Musicpod",
      org: "Ubuntu Community",
      description: "Full Arabic localization with RTL layout support, zero LTR regressions.",
      link: "https://github.com/ubuntu/musicpod",
    },
  ],
  certificates: [
    {
      title: "Head of Flutter",
      issuer: "Benha University",
      date: "Feb 2026",
      image: "Assets/art-gallery/Images/certificates/gdg/Head_Flutter_GDGoC_Certificate.webp"

    },

    {
      title: "The Complete Flutter Development Guide",
      issuer: "Udemy",
      date: "Aug 2025",
      image: "Assets/art-gallery/Images/certificates/flutter/Flutter_Development_Udemy_Certificates.webp",
    },

    {
      title: "The Complete Dart Development Guide",
      issuer: "Udemy",
      date: "Jan 2025",
      image: "Assets/art-gallery/Images/certificates/flutter/Dart Development_Ud_Certificates.webp",
    },

  ],
  artGallery: [
    { src: "Assets/art-gallery/Images/image_display/B2BVBA.png", thumb: "Assets/art-gallery/Images/web/B2BVBA.webp", title: "B2B Visual Analysis" },
    { src: "Assets/art-gallery/Images/image_display/B2BVKW.png", thumb: "Assets/art-gallery/Images/web/B2BVKW.webp", title: "B2B Visual Keyword" },
    { src: "Assets/art-gallery/Images/image_display/B2BVH.png", thumb: "Assets/art-gallery/Images/web/B2BVH.webp", title: "B2B Visual Hub" },
    { src: "Assets/art-gallery/Images/image_display/BFCAI.png", thumb: "Assets/art-gallery/Images/web/BFCAI.webp", title: "BFCAI Identity" },
    { src: "Assets/art-gallery/Images/image_display/BNG1.jpg", thumb: "Assets/art-gallery/Images/web/BNG1.webp", title: "Brand New Generation" },
    { src: "Assets/art-gallery/Images/image_display/BNGKW.jpg", thumb: "Assets/art-gallery/Images/web/BNGKW.webp", title: "BNG Keyword Analysis" },
    { src: "Assets/art-gallery/Images/image_display/BVSarada.jpg", thumb: "Assets/art-gallery/Images/web/BVSarada.webp", title: "Sarada Visual Art" },
    { src: "Assets/art-gallery/Images/image_display/CHM_Makima.jpg", thumb: "Assets/art-gallery/Images/web/CHM_Makima.webp", title: "Chainsaw Man Makima" },
    { src: "Assets/art-gallery/Images/image_display/DS_1.jpg", thumb: "Assets/art-gallery/Images/web/DS_1.webp", title: "Demon Slayer Art" },
    { src: "Assets/art-gallery/Images/image_display/DS_106.png", thumb: "Assets/art-gallery/Images/web/DS_106.webp", title: "Sensei 106 Persona" },
    { src: "Assets/art-gallery/Images/image_display/DS_14.png", thumb: "Assets/art-gallery/Images/web/DS_14.webp", title: "Digital Soul 14" },
    { src: "Assets/art-gallery/Images/image_display/DS_2_BackGround.jpg", thumb: "Assets/art-gallery/Images/web/DS_2_BackGround.webp", title: "Ethereal Background" },
    { src: "Assets/art-gallery/Images/image_display/Free_Palestine_Sensei_Art.png", thumb: "Assets/art-gallery/Images/web/Free_Palestine_Sensei_Art.webp", title: "Free Palestine Art" },
    { src: "Assets/art-gallery/Images/image_display/HG_Logo.jpg", thumb: "Assets/art-gallery/Images/web/HG_Logo.webp", title: "Honor Gallery Logo" },
    { src: "Assets/art-gallery/Images/image_display/Ice_Coffee_Team_Logo.png", thumb: "Assets/art-gallery/Images/web/Ice_Coffee_Team_Logo.webp", title: "Ice Coffee Team" },
    { src: "Assets/art-gallery/Images/image_display/Japan_Coffee_Logo.png", thumb: "Assets/art-gallery/Images/web/Japan_Coffee_Logo.webp", title: "Japan Coffee Logo" },
    { src: "Assets/art-gallery/Images/image_display/Japanese_Girl.jpg", thumb: "Assets/art-gallery/Images/web/Japanese_Girl.webp", title: "Japanese Girl Portrait" },
    { src: "Assets/art-gallery/Images/image_display/JJK_Fight_1.jpg", thumb: "Assets/art-gallery/Images/web/JJK_Fight_1.webp", title: "JJK Fight Scene" },
    { src: "Assets/art-gallery/Images/image_display/JJK_Sensei.jpg", thumb: "Assets/art-gallery/Images/web/JJK_Sensei.webp", title: "JJK Sensei Concept" },
    { src: "Assets/art-gallery/Images/image_display/Mostafa_Logo.png", thumb: "Assets/art-gallery/Images/web/Mostafa_Logo.webp", title: "Mostafa Mahmoud Logo" },
    { src: "Assets/art-gallery/Images/image_display/Naruto_Style.jpg", thumb: "Assets/art-gallery/Images/web/Naruto_Style.webp", title: "Naruto Style Art" },
    { src: "Assets/art-gallery/Images/image_display/Night_Light.png", thumb: "Assets/art-gallery/Images/web/Night_Light.webp", title: "Night Light Concept" },
    { src: "Assets/art-gallery/Images/image_display/Night14.jpg", thumb: "Assets/art-gallery/Images/web/Night14.webp", title: "Nightscape 14" },
    { src: "Assets/art-gallery/Images/image_display/Pizza_Girl.jpg", thumb: "Assets/art-gallery/Images/web/Pizza_Girl.webp", title: "Pizza Girl Illustration" },
    { src: "Assets/art-gallery/Images/image_display/Red_Night.jpg", thumb: "Assets/art-gallery/Images/web/Red_Night.webp", title: "Red Night Concept" },
    { src: "Assets/art-gallery/Images/image_display/sakura.jpg", thumb: "Assets/art-gallery/Images/web/Sakura.webp", title: "Sakura Petals" },
    { src: "Assets/art-gallery/Images/image_display/Sensei_106_Spy.jpg", thumb: "Assets/art-gallery/Images/web/Sensei_106_Spy.webp", title: "Sensei Spy Identity" },
    { src: "Assets/art-gallery/Images/image_display/Sensei_Art44.jpg", thumb: "Assets/art-gallery/Images/web/Sensei_Art44.webp", title: "Sensei Art Archive 44" },
    { src: "Assets/art-gallery/Images/image_display/Tadamon_App_Logo.png", thumb: "Assets/art-gallery/Images/web/Tadamon_App_Logo.webp", title: "Tadamon App Identity" },
  ],
}