import { PortfolioData } from "../types/portfolio";

export const PORTFOLIO_DATA: PortfolioData = {
  profile: {
    name: "Mostafa Mahmoud",
    title: "Senior Software Engineer",
    japaneseTitle: "シニアソフトウェアエンジニア",
    contact: {
      email: "wwwmostafagmer100@gmail.com",
      phone: "+201014414536",
      github: "MostafaSensei106",
      linkedin: "Mostafa Mahmoud",
      location: "Cairo, Egypt",
      whatsapp: "201014414536",
      facebook: "Mostafa.Mahmoud.Sensei",
      x: "Sensei106",
    },
    hero: {
      tagline: "High-Performance Systems & Elegant Mobile Ecosystems.",
      japaneseTagline: "高性能システムとエレガنتなモバイルエコシステム。",
      description: "Dedicated Software Engineer specialized in Flutter, Go, and Rust. Crafting high-performance, concurrent, and scalable solutions with a focus on technical excellence and user experience.",
      photo: "/Assets/art-gallery/Images/logo/Mostafa.jpg", // Changed to the high-res one for optimization later
      cvUrl: "/Assets/cv/Mostafa_Mahmoud_CV.pdf",
    },
  },
  experience: [
    {
      company: "Lothga",
      role: "Flutter Developer [Volunteer]",
      location: "Jeddah, Saudi Arabia, SA",
      period: "Aug 2024 – Aug 2024",
      description: "Engineered the 'LothgaTablet' ecosystem, constructing foundational systems and core kernel features.",
      details: [
        "Developed the project's core and kernel features.",
        "Constructed a foundational system to support the application.",
        "Implemented an audio system to enhance user experience.",
        "Created a central database to integrate all games into a cohesive system.",
        "Enabled parental oversight of children's progress and provided extensive control over game content.",
      ],
      japaneseRole: "フラッターデベロッパー",
    },
    {
      company: "Benha University",
      role: "Bachelor of Computer Science",
      location: "Benha, Egypt",
      period: "Oct 2022 – May 2026",
      description: "Focusing on Software Engineering, Algorithms, and AI.",
      details: [
        "Studying Computer Science, building skills in programming and algorithms.",
      ],
      japaneseRole: "コンピューターサイエンス学士",
      isEducation: true,
    },
  ],
  projects: {
    githubUsername: "MostafaSensei106",
    pinnedRepos: [
      "Network-Reachability",
      "Radix_Plus",
      "FP-Growth",
      "GoPix",
      "Tadamon",
    ],
    highlights: [
      {
        name: "Network-Reachability",
        type: "Dart Package",
        description: "High-performance network monitoring library leveraging a native Rust core to execute complex multi-target probing and DNS resolution.",
        metrics: ["Native Rust Core", "DNS Resolution", "Circuit Breaker"],
        link: "https://github.com/MostafaSensei106/Network-Reachability",
      },
      {
        name: "Radix-Plus",
        type: "Dart Package",
        description: "High-performance sorting library outperforming Dart's native List.sort() by up to 7.0x.",
        metrics: ["~29ms for 1M elements", "Parallel Processing", "Zero-copy operations"],
        link: "https://github.com/MostafaSensei106/Radix_Plus",
      },
      {
        name: "FP-Growth",
        type: "Dart Package",
        description: "High-performance data mining library implementing the FP-Growth algorithm, capable of processing 1,000,000+ transactions in ~1.46s.",
        metrics: ["Isolate Pool", "Memory-optimized", "Data Insights"],
        link: "https://github.com/MostafaSensei106/fp_growth",
      },
      {
        name: "GoPix",
        type: "CLI Tool",
        description: "Blazing-fast image conversion CLI tool supporting multi-format conversion and parallel processing.",
        metrics: ["Parallel Processing", "Multi-Format", "Robust & Reliable"],
        link: "https://github.com/MostafaSensei106/gopix",
      },
      {
        name: "Tadamon",
        type: "Flutter App",
        description: "Helping users make ethical purchasing decisions supporting the Palestinian cause.",
        metrics: ["Offline-First", "Google ML Kit", "BLoC Architecture"],
        link: "https://github.com/MostafaSensei106/tadamon",
      },
    ],
  },
  certificates: [
    {
      title: "The Complete Dart Development Guide",
      issuer: "Udemy / Google Developers",
      date: "2024",
      image: "/Assets/art-gallery/Images/image_display/HG_Logo.jpg",
    },
    {
      title: "The Complete Flutter Development Guide",
      issuer: "Udemy / Google Developers",
      date: "2024",
      image: "/Assets/art-gallery/Images/image_display/HG_Logo.jpg",
    },
  ],
  artGallery: [
    { src: "/Assets/art-gallery/Images/image_display/B2BVBA.png", thumb: "/Assets/art-gallery/Images/web/B2BVBA.webp", title: "B2B Visual Analysis" },
    { src: "/Assets/art-gallery/Images/image_display/B2BVH.png", thumb: "/Assets/art-gallery/Images/web/B2BVH.webp", title: "B2B Visual Hub" },
    { src: "/Assets/art-gallery/Images/image_display/B2BVKW.png", thumb: "/Assets/art-gallery/Images/web/B2BVKW.webp", title: "B2B Visual Keyword" },
    { src: "/Assets/art-gallery/Images/image_display/BFCAI.png", thumb: "/Assets/art-gallery/Images/web/BFCAI.webp", title: "BFCAI Identity" },
    { src: "/Assets/art-gallery/Images/image_display/BNG1.jpg", thumb: "/Assets/art-gallery/Images/web/BNG1.webp", title: "Brand New Generation" },
    { src: "/Assets/art-gallery/Images/image_display/BNGKW.jpg", thumb: "/Assets/art-gallery/Images/web/BNGKW.webp", title: "BNG Keyword Analysis" },
    { src: "/Assets/art-gallery/Images/image_display/BVSarada.jpg", thumb: "/Assets/art-gallery/Images/web/BVSarada.webp", title: "Sarada Visual Art" },
    { src: "/Assets/art-gallery/Images/image_display/CHM_Makima.jpg", thumb: "/Assets/art-gallery/Images/web/CHM_Makima.webp", title: "Chainsaw Man Makima" },
    { src: "/Assets/art-gallery/Images/image_display/DS_1.jpg", thumb: "/Assets/art-gallery/Images/web/DS_1.webp", title: "Demon Slayer Art" },
    { src: "/Assets/art-gallery/Images/image_display/DS_106.png", thumb: "/Assets/art-gallery/Images/web/DS_106.webp", title: "Sensei 106 Persona" },
    { src: "/Assets/art-gallery/Images/image_display/DS_14.png", thumb: "/Assets/art-gallery/Images/web/DS_14.webp", title: "Digital Soul 14" },
    { src: "/Assets/art-gallery/Images/image_display/DS_2_BackGround.jpg", thumb: "/Assets/art-gallery/Images/web/DS_2_BackGround.webp", title: "Ethereal Background" },
    { src: "/Assets/art-gallery/Images/image_display/Free_Palestine_Sensei_Art.png", thumb: "/Assets/art-gallery/Images/web/Free_Palestine_Sensei_Art.webp", title: "Free Palestine Art" },
    { src: "/Assets/art-gallery/Images/image_display/HG_Logo.jpg", thumb: "/Assets/art-gallery/Images/web/HG_Logo.webp", title: "Honor Gallery Logo" },
    { src: "/Assets/art-gallery/Images/image_display/Ice_Coffee_Team_Logo.png", thumb: "/Assets/art-gallery/Images/web/Ice_Coffee_Team_Logo.webp", title: "Ice Coffee Team" },
    { src: "/Assets/art-gallery/Images/image_display/Japan_Coffee_Logo.png", thumb: "/Assets/art-gallery/Images/web/Japan_Coffee_Logo.webp", title: "Japan Coffee Logo" },
    { src: "/Assets/art-gallery/Images/image_display/Japanese_Girl.jpg", thumb: "/Assets/art-gallery/Images/web/Japanese_Girl.webp", title: "Japanese Girl Portrait" },
    { src: "/Assets/art-gallery/Images/image_display/JJK_Fight_1.jpg", thumb: "/Assets/art-gallery/Images/web/JJK_Fight_1.webp", title: "JJK Fight Scene" },
    { src: "/Assets/art-gallery/Images/image_display/JJK_Sensei.jpg", thumb: "/Assets/art-gallery/Images/web/JJK_Sensei.webp", title: "JJK Sensei Concept" },
    { src: "/Assets/art-gallery/Images/image_display/Mostafa_Logo.png", thumb: "/Assets/art-gallery/Images/web/Mostafa_Logo.webp", title: "Mostafa Mahmoud Logo" },
    { src: "/Assets/art-gallery/Images/image_display/Naruto_Style.jpg", thumb: "/Assets/art-gallery/Images/web/Naruto_Style.webp", title: "Naruto Style Art" },
    { src: "/Assets/art-gallery/Images/image_display/Night_Light.png", thumb: "/Assets/art-gallery/Images/web/Night_Light.webp", title: "Night Light Concept" },
    { src: "/Assets/art-gallery/Images/image_display/Night14.jpg", thumb: "/Assets/art-gallery/Images/web/Night14.webp", title: "Nightscape 14" },
    { src: "/Assets/art-gallery/Images/image_display/Pizza_Girl.jpg", thumb: "/Assets/art-gallery/Images/web/Pizza_Girl.webp", title: "Pizza Girl Illustration" },
    { src: "/Assets/art-gallery/Images/image_display/Red_Night.jpg", thumb: "/Assets/art-gallery/Images/web/Red_Night.webp", title: "Red Night Concept" },
    { src: "/Assets/art-gallery/Images/image_display/sakura.jpg", thumb: "/Assets/art-gallery/Images/web/Sakura.webp", title: "Sakura Petals" },
    { src: "/Assets/art-gallery/Images/image_display/Sensei_106_Spy.jpg", thumb: "/Assets/art-gallery/Images/web/Sensei_106_Spy.webp", title: "Sensei Spy Identity" },
    { src: "/Assets/art-gallery/Images/image_display/Sensei_Art44.jpg", thumb: "/Assets/art-gallery/Images/web/Sensei_Art44.webp", title: "Sensei Art Archive 44" },
    { src: "/Assets/art-gallery/Images/image_display/Tadamon_App_Logo.png", thumb: "/Assets/art-gallery/Images/web/Tadamon_App_Logo.webp", title: "Tadamon App Identity" },
  ],
  theme: {
    colors: {
      primary: "#E31E24", // Samurai Red
      secondary: "#1A1A1A",
      accent: "#FFD700", // Gold accent for high quality feel
      background: "#000000",
      surface: "#121212",
      text: "#FFFFFF",
    },
    borderRadius: {
      base: "0px", // Samurai/Traditional Japanese often uses sharp edges
      card: "4px",
      button: "2px",
    },
  },
};
